### ISSUE TITLE
Inconsistencies in VS compilation versions

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#105]
There is a mix of VS environments in the XWord tree:

- The app is built against VS2010 (in the AppVeyor builds configured in my fork). We probably don't want to revert back to an older version at this point - for one, the "dpiawareness" support in premake5 requires VS2010+, but also that version is already quite old.
- The distribution setup includes VS2008 redistribution DLLs - this is because lua51.dll is built against them.
- Other DLLs (libcurl, zlib) link against msvcrt.dll, which looks like VS 6.0. But it looks like this is probably bundled with Windows already.

Do we also need to bundle the VS2010 runtime, given that dropping to VS2008 is probably not an option?

**Comment by jpd236** [comment]
One annoying thing here is that the free/express edition of VS2010 doesn't appear to include the redist files, even though both older and newer ones do: https://stackoverflow.com/questions/25687530/my-installation-of-visual-studio-2010-express-doesn-t-include-a-redist-folder

I don't think I had a strong reason for picking vs2010 specifically; I think it was the newest VS version supported by premake4 at the time I started working on this. Now that we're on premake5, perhaps it would be best to recompile everything w/ vs2019, use it for AppVeyor, and include the needed runtime with it.

**Comment by mrichards42** [comment]
Yuck, what a mess. Yeah, it probably makes the most sense to compile everything with the same version of VS and then include a single redist package. At some point way back when I think I was trying to compile everything with a version of VS old enough that most windows versions would have included an appropriate CRT version and I wouldn't have to package any of them, but obviously that was misguided.

I wonder if we might want to end up going with a C/C++ package manager eventually so there aren't a bunch of precompiled binaries in source control.
