### ISSUE TITLE
Crash when rapidly loading files on Mac (due to Lua)

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#121]
By doing the following:

1. Open file
2. Make some changes
3. Open another file (in Finder)
4. Quickly press enter before the save dialog appears (will save changes)

and repeating a few times, I can consistently reproduce a hang in XWord. When it doesn't hang, I see some errors in various plugins which suggests to me that plugins are trying to access destroyed state from the previous puzzle (or something along those lines).

The hang becomes significantly less frequent with the graph plugin disabled, but unfortunately it's not a 100% fix, and I see Lua errors in more critical plugins like import.

Graph plugin Lua error:

```
08:40:03 PM: (error) Lua: Error while running chunk
...ations/XWord.app/Contents/PlugIns/scripts/graph/init.lua:98: method GetIsMissing does not exist
stack traceback:
	[C]: in function '__index'
	...ations/XWord.app/Contents/PlugIns/scripts/graph/init.lua:98: in function 'make_point'
	...ations/XWord.app/Contents/PlugIns/scripts/graph/init.lua:123: in function <...ations/XWord.app/Contents/PlugIns/scripts/graph/init.lua:114>
```

Import plugin:
```
08:43:59 PM: (error) Lua: Error while running chunk
Invalid encoding
stack traceback:
	[C]: at 0x0110e77460
	[C]: in function '__index'
	...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:60: in function 'func'
	...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:50: in function 'iter_clues'
	...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:58: in function 'find_clues'
	...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:70: in function <...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:32>

08:44:00 PM: (error) Lua: Error while running chunk
...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:40: method GetSetTheme does not exist
stack traceback:
	[C]: in function '__index'
	...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:40: in function <...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:37>
```

**Comment by mrichards42** [comment]
I must not have been persistent enough trying to reproduce the hang, but I'll give it another shot. FWIW I've experienced a persistent but extremely rare issue similar to this for years where I'll get a random lua error just like this. Never a crash or a hang, but the actual lua error is basically the same. I also very occasionally can produce one by trying to download a ton of files at once, or quickly moving the cursor between dates in the downloader to show the puzzle preview.

Here's what's always confused me -- the metatable's `__index` function is what transforms `square.xyz` into `square.GetXyz` ([function here](https://github.com/mrichards42/xword/blob/811a30707515b0a3355cccd80917c33f8e7e6eea/lua/luapuz/luapuz_functions.hpp#L217) and registration in the metatable [here](https://github.com/mrichards42/xword/blob/689e3a3336d39c0c041ff9353096660314ddb145/lua/luapuz/bind/luapuz_puz_Square.cpp#L860)) . . . but the square's metatable _also_ has all of those functions registered ([here](https://github.com/mrichards42/xword/blob/689e3a3336d39c0c041ff9353096660314ddb145/lua/luapuz/bind/luapuz_puz_Square.cpp#L835)), so if it can't find `IsMissing` in the metatable I don't know why it still has the same `__index` in the metatable.

Maybe some very verbose logging before the error at the end of `luapuz_index` might be helpful.

**Comment by jpd236** [comment]
I could probably capture a video of the exact pattern of opening files that leads to the crash, if you're not able to reproduce it with the above steps. (Can also reproduce with more verbose logging enabled).

**Comment by mrichards42** [comment]
I've managed to reproduce with your instructions. I think I was giving up too quickly before, but I can get the hang consistently now by rapidly opening files either through Finder or downloader way and hitting `Enter` before the dialog pops up.

**Comment by mrichards42** [comment]
And I think what's going on is there's a race somewhere that causes the wrong metatable to be set.

Both of the lua errors you posted above are probably a Square that ended up with the Clue metatable, which doesn't have IsMissing or SetTheme functions:
```
...ations/XWord.app/Contents/PlugIns/scripts/graph/init.lua:98: method GetIsMissing does not exist
...ions/XWord.app/Contents/PlugIns/scripts/import/theme.lua:40: method GetSetTheme does not exist
```

I was able to examine a couple hangs in a debugger, and they all seemed to be coming from a call to the luapuz function [`Square_GetText`](https://github.com/mrichards42/xword/blob/811a30707515b0a3355cccd80917c33f8e7e6eea/lua/luapuz/bind/luapuz_puz_Square.cpp#L158) inside `import.mark_theme_squares` . . . except there aren't any calls to that function in mark_theme_squares, only calls to [get _clue_ text](https://github.com/mrichards42/xword/blob/811a30707515b0a3355cccd80917c33f8e7e6eea/scripts/import/theme.lua#L60). The square in question has gibberish for all its fields, but casting it to `puz::Clue *` shows `number` as a real clue number and `text` as the real clue text.

I have no idea how this could be happening, but if metatables are getting swapped around it would definitely explain the errors I've seen for years. I'd be curious to swap out LuaJIT for vanilla lua and see if it fixes things.

**Comment by mrichards42** [comment]
@jpd236 I forgot about this issue, but adee03744e881b1014288b4e96c05d142941e48b might fix it.
