### ISSUE TITLE
Refine selection of initial square

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#134]
Currently, when you open a puzzle file, XWord searches for the first white square in the grid (from the top left) and sets focus to the word containing that square in the Across direction. (See XGridCtrl::SetPuzzle). This typically works fine, but can result in some strange behavior for grids with non-standard numbering, e.g. a Snake Charmer JPZ file where the first clue is typically in the middle of the top row.

Perhaps it would be a bit more general to use the first clue in the first clue list? It feels like this should work the same way for a typical crossword grid while being a bit more likely to be reasonable for variant formats. But if that seems like it might cause a regression elsewhere, we could narrow the scope a bit, e.g. by only using this alternate logic for puzzles with one clue list (where it's unambiguous which clue is "first").

**Comment by mrichards42** [comment]
I think this is a great idea. How about this?

* If there is only one clue list, that's it
* If there are multiple lists, but one of them is "Across", use that list
* Otherwise, I guess pick the first one alphabetically? Or randomly?

**Comment by jpd236** [comment]
#136 should implement the first two of those - wanted to be conservative to start. I'm not sure offhand of a canonical "first" list for other puzzle types, or if there's perfect consistency in the naming for those lists since it's just a freeform string (and since different puzzle types might have overlapping cluelist names - e.g. "Rows" in both Marching Bands and Rows Garden puzzles). And I'm not sure picking the first list alphabetically would give better results than the current heuristic, since it feels similarly arbitrary.

In any case, hopefully this is a good start which gives us a place to add further heuristics later if we see a safe way to do so. And if you're feeling better than I am about those other two rules, I'd be happy to add them.

**Comment by jpd236** [comment]
One thought is if we can (or already do?) retain the clue list order from the JPZ file, picking the first list in that file might be a reasonable implementation. At the moment, IIRC, I don't think we do so - at least in terms of how we render the clue lists in the UI.

**Comment by mrichards42** [comment]
That looks like a good compromise since it should cover by far the most common cases, thanks!
