### ISSUE TITLE
Clue list name matching for PUZ conversion is case sensitive

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#140]
If you open a JPZ file whose clue list names are "ACROSS" and "DOWN" - which appears to be the default naming used by Crossword Compiler - and try to save it as a PUZ file, the conversion will fail stating that the puzzle uses features not supported by the PUZ format. But this is only because the saver expects exactly "Across" and "Down". It should be possible to relax the match here.

**Comment by jpd236** [comment]
I tried what seems like the obvious solution here - making Clues a case-insensitive map by passing in a custom compare function. Somehow this leads to a crash in the AUI manager when opening a puzzle with "ACROSS" and "DOWN" instead of "Across" and "Down", but I'm not immediately sure why. I imagine this is something silly I did or is otherwise fixable, hopefully.

The other hack would just be to normalize the clue list names when loading, but that doesn't seem ideal as you're changing the provided file.

**Comment by jpd236** [comment]
Another issue with saving a JPZ as a PUZ - XWord supports reading notes from a number of different fields, but only saves the notes to a puz if they came from the `<instructions>` tag. The other fields (different metadata attributes) are ignored. In principle, I think it makes sense for whichever notepad XWord decides to display to also be saved to the PUZ file.

**Comment by mrichards42** [comment]
> The other hack would just be to normalize the clue list names when loading, but that doesn't seem ideal as you're changing the provided file.

You _might_ be able to normalize just the keys to `Clue` but leave `ClueList.m_title` as is. Or maybe even a new member var in ClueList that marks it as across or down? Those are all hacks, but 🤷 maybe? Or honestly I don't think `Clues::GetClueList` is used all that often, and I doubt it's in a tight loop anywhere, so it wouldn't be the end of the world to just do the normalization on the fly in that function.

> Another issue with saving a JPZ as a PUZ - XWord supports reading notes from a number of different fields, but only saves the notes to a puz if they came from the <instructions> tag. The other fields (different metadata attributes) are ignored. In principle, I think it makes sense for whichever notepad XWord decides to display to also be saved to the PUZ file.

Makes sense to me.
