### ISSUE TITLE
Some New Yorker puzzles are failing to download w/ downloader

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#144]
Examples:

https://www.newyorker.com/puzzles-and-games-dept/crossword/2021/06/02
https://www.newyorker.com/puzzles-and-games-dept/crossword/2021/05/26

The error just says "File does not exist", so I'm not sure what's going wrong. If I had to guess, given the inconsistent nature of the issue (since some puzzles download just fine), I'd predict some use of either special characters or HTML tags that's throwing off the converter.

**Comment by mrichards42** [comment]
Ah yeah, at least one of those is a puzzle without cellInfos. I have a fix for at somewhere, but more to the point that's a pretty bad error message :)

**Comment by jpd236** [comment]
BTW, you might also be interested in this comment thread:

https://www.reddit.com/r/crossword/comments/nif819/downloading_new_yorker_puzzles_puzjpzetc_any_ideas/gz1r6x7/?utm_source=reddit&utm_medium=web2x&context=3

Someone mentioned trying to update the download URL to match a recent fix you made to the downloader and getting a Lua error. I wasn't able to reproduce it, though.

**Comment by mrichards42** [comment]
Huh, yeah I haven't come across that before, although admittedly that downloader config is probably kind of brittle.

**Comment by mrichards42** [comment]
Ok, this should be fixed in 31c1b2b298017df96f15ffba630d8bef46603ba5, plus better error reporting in 0dbcfea716a2b95191780c3ea4026cd7abd8d173
