### ISSUE TITLE
Italicized clues are cut off on Mac

### ISSUE THREAD

**Issue by crosswordnexus** [mrichards42/xword#158]
![Screen_Shot_2021-08-13_at_3 21 07_PM](https://user-images.githubusercontent.com/11986670/129428622-db8af51c-fcb0-4e41-bd84-cb1286a914d1.png)

This happens in both the top clue pane and the side panes.  To my knowledge this does not happen on Windows.

**Comment by mrichards42** [comment]
I'm guessing this is a bug in wxWidgets, though it's possible something about that HTML renderer is configured incorrectly in my code. It kind of looks like text of each style (regular, italic) is rendered to a bitmap and then blitted to the screen, but with the wrong blending mode, so the background is chopping off the last letter of the italics.

I can get this to happen on Windows as well, if I change the font. Likely Mac defaults to Hevetical and Windows to Arial, and setting Helvetica on Windows does cause the same behavior. But curiously even with the same font the text slants _way_ more on Mac than on Windows.
