### ISSUE TITLE
Attribution not filling in for acrostic puzzles

### ISSUE THREAD

**Issue by crosswordnexus** [mrichards42/xword#183]
See e.g. https://crosswordnexus.com/x/jpz/94b5d89d4d0a9a148bebc9e01a4e8101.jpz

Ideally all letters with the same number would highlight and auto-fill.

**Comment by jpd236** [comment]
It's working fine for me - e.g. if I select the letter of one of the clues, I see three highlighted squares - that letter, the letter in the quote, and the letter in the attribution - and typing a letter shows up in all three places. If you're using 0.7.0, does it work for you with a newer release from https://github.com/jpd236/xword/releases? Though I can't find a commit that would explain why it'd be fixed.

**Comment by boisvert42** [comment]
I am in fact using 0.7.0.  I'll try one of your releases.

**Comment by boisvert42** [comment]
Yep, it works there. This can be safely closed.
