### ISSUE TITLE
Allow for colored blocks

### ISSUE THREAD

**Issue by boisvert42** [mrichards42/xword#189]
![image](https://user-images.githubusercontent.com/6503071/166129928-3d4f26cb-6996-4afc-ab05-0c41281cf39c.png)
Using background-color in JPZ/XML files allows you to change the color of "black" squares in Crossword Solver and ideally the same would happen in XWord. See example.

**Comment by jpd236** [comment]
I think this is fixed in tip-of-tree. It works for me from there but not 0.7.0.

**Comment by boisvert42** [comment]
Gotcha! I didn't realize I was still on 0.7.0. I'll upgrade.
