### ISSUE TITLE
'Unknown file type' on XML puzzles

### ISSUE THREAD

**Issue by fakelvis** [mrichards42/xword#205]
When attempting to open some XML puzzles, an 'Unknown file type' error message is raised.

For Universal Daily, as an example, the puzzles downloaded since December 21 (inclusive) cause this problem.

----

Just in case it's a local-only problem, I've attached the Universal Daily puzzles of 20 and 21 December as I have them. Both downloaded via XWord, where one opens and the other does not.

[UniDaily Dec20and21.zip](https://github.com/mrichards42/xword/files/10329550/UniDaily.Dec20and21.zip)

My knowledge on all things file encoding is lacking/absent, but that does seem to be different in these two files. I recently updated to the new release, but I can't recall if that was the same date, unfortunately.

**Comment by jpd236** [comment]
FWIW, the downloader is working fine for me for the Universal Daily puzzles on both those days as well as today.

The attached files both open for me as well, but the 12/20 file isn't actually an XML file - it's an Across Lite .puz file with a .xml file extension. Not sure how it got into that state.

**Comment by fakelvis** [comment]
I did a reinstall on both version 0.8.1 and 0.7.4 and still experienced this problem when attempting to open the actual XML files (so Dec 21 onwards).

However, after another uninstall and reinstall (this time of the portable version of 0.7.4, but I don't believe that's actually material here) it's all back to normal: opening the XML files now works as normal.

It looks like this was some stuck configuration or weird local-specific problem that solved itself. As I can no longer reproduce this, I'll close this. Apologies, all!
