### ISSUE TITLE
Import package not loading

### ISSUE THREAD

**Issue by lukewarmandbothered** [mrichards42/xword#206]
On a new PC running Windows 11, I get an error starting the import package. Log file details below:

------------------------
Lua log for 03/16/23
==========================================================
09:57:28: Package 'import' is disabled because of an error while loading the package:
C:\Program Files (x86)\XWord\scripts\import\init.lua:50: module 'import.amuselabs' not found:
	no field package.preload['import.amuselabs']
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs.lua'
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs\init.lua'
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs\import\amuselabs.lua'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs.lua'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs\init.lua'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs\import\amuselabs.lua'
	no file 'C:\Program Files (x86)\XWord\import\amuselabs.dll'
	no file 'C:\Program Files (x86)\XWord\import\amuselabs51.dll'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs.dll'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs51.dll'
	no file 'C:\Program Files (x86)\XWord\import.dll'
	no file 'C:\Program Files (x86)\XWord\import51.dll'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import.dll'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import51.dll'
	no file './import\amuselabs.fnl'
	no file './import\amuselabs/init.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs\init.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\import\amuselabs\import\amuselabs.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs\init.fnl'
	no file 'C:\Program Files (x86)\XWord\scripts\libs\import\amuselabs\import\amuselabs.fnl'
stack traceback:
	[C]: in function 'require'
	C:\Program Files (x86)\XWord\scripts\import\init.lua:50: in main chunk
	[C]: at 0x7bf4a280
	[C]: in function 'xpcall'
	C:\Program Files (x86)\XWord\scripts\xword\pkgmgr\load.lua:19: in function 'load_package'
	C:\Program Files (x86)\XWord\scripts\xword\pkgmgr\load.lua:66: in function 'load_packages'
	C:\Program Files (x86)\XWord\scripts/xword/init.lua:104: in main chunk
--------------------------

Thanks!

**Comment by lukewarmandbothered** [comment]
I was able to find and resolve the issue. The "amuselabs.lua" file was missing from "C:\Program Files (x86)\XWord\scripts\import" so I copied it over from my old PC, manually enabled the Import package, restarted XWord and all is good now. For what it's worth, I uninstalled/reinstalled (even re-downloaded the install file) multiple times, to no avail.

**Comment by ayryq** [comment]
I have the same issue with a new install—and I don't have an old PC to copy it over from.

**Comment by mrichards42** [comment]
Hey @ayryq sorry, this should be fixed in #209 but we haven't cut a new release since then. In the mean time you should be able to use an installer from the latest main branch build, which is here: https://ci.appveyor.com/api/buildjobs/gynbud2b88gxa9f6/artifacts/dist%2FXWord-Windows.exe

**Comment by thegreatuploader** [comment]
I am having the same issue and the appveyor link no longer works
