### ISSUE TITLE
Plugins beginning with "_" still show up in release builds

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#34]
This commit: https://github.com/mrichards42/xword/commit/de634a7ab9a5da4180f1ff5c1fc6833f9f30826a

Purported to remove the _swap script "from production". However, I still see it loaded by default on release builds, with my packages.lua config erased.

What does "remove from production" mean if not this?

Relatedly, is it expected that in Lua-enabled release builds, the "Debug" menu shows up due to the xworddebug plugin being loaded by default?

**Comment by mrichards42** [comment]
The original intention was to distribute only a minimal set of scripts (xword, libs, and import), and allow users to download packages individually.  I'm not set on doing it this way -- the entire scripts directory is like 100k zipped -- but that's how I've been doing it.

The dist directory (which is messy and pretty windows-specific, but that's another story) has a script to generate a package list and a zip for each package.  It excludes '_' prefixed scripts, so they were never uploaded to sourceforge for distribution.  XWord.nsi lists the scripts included by default.

Anything you have in the scripts directory is loaded on start (unless it's disabled), so yes, xworddebug can be used in a release build as well, but it isn't included in the distribution.

**Comment by jpd236** [comment]
Gotcha.

Will close this out as I suppose it's reasonable to choose which scripts to include at distribution time and just include everything in development builds.

I'll file a separate bug to figure out the dist process in the new GitHub+Mac world.
