### ISSUE TITLE
Clue display stops updating after cancelling opening another puzzle

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#55]
- Open a puzzle and make some changes
- Start to open another puzzle, prompting the unsaved changes dialog
- Cancel the dialog

At this point, the highlighted clue never updates even as the cursor moves around the grid.

Furthermore, if you now open another puzzle and opt not to save the previous one, the grid never gets fully repainted and instead reflects the previous puzzle's grid.

 (Tested on Mac)

**Comment by mrichards42** [comment]
Well that's a silly bug.  Fixed in 89f6fa07b001affad3ce53add28d445910ac3b75

**Comment by jpd236** [comment]
Thanks!
