### ISSUE TITLE
Timer is truncated when paused on macOS

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#6]
On macOS, the timer ends up being truncated when paused:

<img width="125" alt="screen shot 2016-10-09 at 12 35 54 pm" src="https://cloud.githubusercontent.com/assets/4713321/19223142/01ce7194-8e1d-11e6-8ec8-fb451d0854de.png">

The layout currently sets the timer's left edge to a fixed position from the right edge of the window.

The quick fix is to just move this fixed position further to the left, either globally or on macOS only.

A cleaner fix might be to align the timer to the right edge of the window, so its margin always matches the margin from the left edge of the status bar to the left edge of the status message. Unfortunately, this might be a bit trickier. Here are some thoughts on how to do this which might be helpful:

http://stackoverflow.com/questions/13210822/how-can-i-align-the-text-in-a-statusbar-to-the-right-in-wxpython

**Comment by mrichards42** [comment]
Merged the quick fix, but it would be worth trying to right-align the timer.
