### ISSUE TITLE
Add support for rgz format

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#86]
.rgz is a new format for Rows Garden puzzles which appears to have been introduced for an [Android/iOS app](https://play.google.com/store/apps/details?id=edu.stanford.cs.bosch.rowsgarden&hl=en_US). I didn't find any official documentation, but the format seems pretty straightforward; it's a zip file containing a text file with some puzzle metadata, the row clues and answers, and the light, medium, and dark bloom answers, each in order from left-to-right, top-to-bottom. I think in principle you could have different size grids, but in practice I've never seen a file in this format that didn't follow the "standard size".

It should be possible to read these files into XWord; for example, [Outside the Box puzzles](http://www.joonpahk.com/blog/) distributes Rows Garden puzzles as JPZ files which XWord has no trouble with.

Some notes:

- We'd need to pick colors for the light/medium/dark blooms
- We might want to automatically add word count and hyphenation indicators to clues based on the answers, since I think the app does this or at least gives the option to. Note that multi-word/hyphenated answers are put in the .rgz file with spaces/hyphens, which should be stripped out for the actual grid.
-  Asterisks in clues denote italicized text (e.g. titles)

Should this be an import script or a full-fledged native format? I lean towards import to jpz, since I have no idea what it would look like to save a .rgz file with partial entries.

Example puzzles are available [here](https://www.ariespuzzles.com/p/archive.html).

**Comment by mrichards42** [comment]
Have you solved JPZ rows gardens in XWord? This is the first I've even seen rows garden puzzles, but I think it would take a good bit of work to implement an interface since it uses a hexagon grid instead of a square grid.

**Comment by jpd236** [comment]
There's actually a neat translation to a rectangular grid structure, which is how Outside the Box puzzles distributes jpz files. You can see how it looks here: http://www.joonpahk.com/solver/?puztype=rows_garden&filename=filer_public%2F5e%2Fbf%2F5ebfc882-9f5d-4a9a-b295-ef9d659ff429%2Fotb_sample_r.xml

**Comment by mrichards42** [comment]
Oh slick, thanks for the example. If there's a straightforward conversion to a rectangular grid, works for me. I agree that an import script makes the most sense. Looks like it's a zipped yaml file to me.

**Comment by jpd236** [comment]
Been working on this and had a few questions/observations:

- I didn't see any functional pure Lua implementations of YAML parsing or zip file reading, so my plan is to find reasonable native libraries with Lua bindings and take a similar approach to yajl - native library + native code from Lua library + lua library. I've got this working locally so far for YAML parsing, but do you have any concerns? There's an implementation of minizip which is private to the puz library; maybe I can factor that out into a shared library.

- I'm having a bit of trouble figuring out how to push custom words for the puzzle. For each clue, I need to be able to push a custom set of squares corresponding to the answer. I think I need to add some bindings to luapuz to make this possible - I think Word needs the `push_back(Square* square)` function exposed so that I can create a Word with a custom list of squares, and Clue needs the Word property exposed so I can set the custom Word. Does that sound right to you? If so, how do you actually regenerate the luapuz bindings? I see the scripts (e.g. lua/luapuz/bind/init.lua) but couldn't figure out the right invocation to run them.

- Some follow-up things to look at: if you try to open the rgz file in XWord through Windows, it just opens a blank window. The import plugin only seems to work when opening the file from inside XWord. Also, the open dialog doesn't specify formats which are supported by the import plugin, so files don't show up unless you change the filter to all files first.

**Comment by jpd236** [comment]
Ah, looks like puz_defs.lua is the script to run to generate the bindings.

**Comment by mrichards42** [comment]
> There's an implementation of minizip which is private to the puz library; maybe I can factor that out into a shared library.

I dug into this a little yesterday and remembered that wxLua is built against zlib. The xword package manager is supposed to be able to install from a variety of zip formats. Here's the code it uses to set up wxFileSystem to handle archives. It might make sense to factor this out somewhere so that it isn't dependent on script load order, Or maybe it's possible to use wxArchiveFSHandler without all that setup code? 

https://github.com/mrichards42/xword/blob/fc66fe5578354327f8fe860da9c7392300084e76/scripts/xword/pkgmgr/install.lua#L78-L95


> my plan is to find reasonable native libraries with Lua bindings and take a similar approach to yajl - native library + native code from Lua library + lua library. I've got this working locally so far for YAML parsing, but do you have any concerns?

Nope, that sounds perfectly reasonable.

> I think Word needs the push_back(Square* square) function exposed so that I can create a Word with a custom list of squares, and Clue needs the Word property exposed so I can set the custom Word. 

IIRC, I tried to use tables for some of the puzzle data to make it easier to work with in lua. I believe that's what all the "typedefs" are in puz_defs.lua. The typedefs include custom functions (in puz_overrides.lua) that convert from lua -> c++ (check_func) and from c++ -> lua (push_func).

Also I don't _think_ any of the importers operate on the puz::Clue or puz::Word level; instead they build up a lua table that functions as a ClueList, and then set that table in `puz::SetClueList`. So the simplest thing to do would probably be:

1. Add `luzpuz_checkWord` to the Word typedef, so you can treat a table of squares as a Word
2. Edit `luapuz_checkClueList` so that it parses words from each clue table, probably at the end of this block: https://github.com/mrichards42/xword/blob/fc66fe5578354327f8fe860da9c7392300084e76/lua/luapuz/bind/puz_overrides.lua#L529-L544

> Also, the open dialog doesn't specify formats which are supported by the import plugin, so files don't show up unless you change the filter to all files first.

Huh, I don't think I realized the format string is hard-coded. It should be as simple as reading the `import.handlers` lua table and grabbing extensions and descriptions from there as well (or maybe even simpler to write a lua function to generate the format string, and call that function from the c++ side, similar to how MyFrame::LoadPuzzle works).

Looks like this is the code we'd need to change:
https://github.com/mrichards42/xword/blob/fc66fe5578354327f8fe860da9c7392300084e76/src/MyFrame.cpp#L463-L476


> if you try to open the rgz file in XWord through Windows, it just opens a blank window. The import plugin only seems to work when opening the file from inside XWord. 

Ah, it looks like we're calling `puz::Puzzle::CanLoad` directly when parsing cli args instead of using the lua version. Might be simplest to just remove that check and try to load whatever file you send XWord.

https://github.com/mrichards42/xword/blob/fc66fe5578354327f8fe860da9c7392300084e76/src/App.cpp#L181

**Comment by jpd236** [comment]
Thanks! Will take a closer look at wxFileSystem and the issues with import handlers and app open once I have the basics in place on uncompressed rg files.

My WIP is at https://github.com/mrichards42/xword/commit/a7aecf8f12d0af28383434694b507d8f8b9b436b; I took a try at making the changes you described to `puz_overrides.lua`, but I seem to have gotten something wrong either in there or in the rgz import script, because I get an access violation (perhaps due to trying to read a nil pointer?) in the generated luapuz_checkWord function on the very first call to lua_next in that function.

**Comment by mrichards42** [comment]
Hmm, nothing obvious jumps out at me from the generated files. Does that happen for the first clue you try to set, or are you able to process _some_ clues? I'm surprised you'd get a segfault instead of a lua error.

This might be a minimal test to make sure it isn't the import script:

```lua
local p = puz.Puzzle()
p.Grid:SetSize(21, 12)
p:SetClueList('test', {{text="testing", word={p.Grid:First(), p.Grid:First():Next()}}})
```

**Comment by jpd236** [comment]
Confirmed with both a debugger and some print statements that it's the first call to lua_next inside luapuz_checkWord that's failing.

I get a different failure when I try to run that script in the testing interpreter:

```bad argument #9 to 'SetClueList' (puz.Square expected, got number)```

Not sure yet why, but wondering if that has something to do with the use of tables for puz.Square?

**Comment by jpd236** [comment]
Dug some more but still don't really have much insight here; just a couple observations:

- When using the interpreter with this sample code, inside luapuz_checkClueList, luapuz_isClue returns true. That seems to hit a different codepath than the one I was seeing with the rgz script, where it reads the clue object directly via luapuz_checkClue rather than the code I changed to read the word from a table. Seems to fail in the same way even when I skip that code and have it follow my code instead - it gets further and does enter the loop, but fails to read the first square due to the type check in luapuz_checkSquare.

- Visual Studio's debugger seems to be a bit strange and shows garbage values for the grid state (e.g. width/height) in the call to SetClueList, even though they looked normal after the call to set the dimensions of the grid. But the value (e.g. width) seems to become normal when returned to Lua and printed in the interpreter. This may just be an issue with the debugger or how I'm looking at it, but noting it because it might be relevant for the access exception?

**Comment by jpd236** [comment]
I think this was a bug in luapuz_checkSquareVector that I copied over to luapuz_checkWord. If a negative stack index is provided as the location of the word to read, we'll be off by one because we push a nil at the top of the stack at the beginning of loop iteration.

We could either convert to absolute indexes manually, or, based on https://jorgar.tumblr.com/post/149905757959/dealing-with-relative-indices-in-lua-apis, just copy the table to the top of the stack and use that copy as a cleaner if marginally less efficient solution.

**Comment by mrichards42** [comment]
That `lua_next` loop is copied right from the [docs](https://www.lua.org/manual/5.1/manual.html#lua_next), so I doubt that's it. If we're doing a lot of stack manipulation, that blog post is probably accurate.

According to the docs, `lua_next` pops the key first, then checks the table at `index`, then pushes a key and value. So I'm assuming this order of operations:

```c
lua_pushnil(L) // stack is off by 1

while (lua_next(L, index) != 0) {
    /* pseudo-code for lua_next */
    prev_key = pop(L, -1) // stack is back to how we started
    key, value = next_pair_for_table(L, index, prev_key) // so index is valid again
    push(L, key) // stack is off by 1
    push(L, value) // stack is off by2

    // then the user code does this:
    value = pop(L, -1) // stack is off by 1

   // then back to the next iteration, which starts by popping the key off the stack
}

**Comment by mrichards42** [comment]
I probably can't get to it this week, but I'll try to take a deeper dive the following week

**Comment by jpd236** [comment]
Empirically speaking, I don't think the behavior you're assuming is what's happening. The code from the docs works fine if index is positive, but fails if it's negative. It appears that lua_next first converts the provided index to an absolute index before popping the top value. I have everything working end-to-end now that I've changed this to handle negative values differently (by following the blog post's suggestion of copying the value first, though there are other ways).

https://github.com/jpd236/xword/commit/rgz-support is functional for both .rg and .rgz files (tested on about 20 different rgz files from both Outside the Box and Aries Puzzles), and is compiling on both platforms in CI. I need to take a review pass and also split it into smaller pieces before I send it out. There's also a bit of an issue with saving puzzles with italicized text; I've replaced "\*text\*" with "<i>text</i>" and it works fine on import, but the clues lose text when I save to JPZ. I need to look into how JPZ is supposed to handle italicized clues (if at all).

**Comment by mrichards42** [comment]
No, you're right. That seems like a pretty big gotcha to leave out of the docs. The way I read this, the table index is checked first: https://github.com/lua/lua/blob/v5.1.1/lapi.c#L970-L972

Fortunately those look like the only two `lua_next` calls in the puz library.
