### ISSUE TITLE
Rebus square entry is difficult on macOS

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#9]
- The insert key is used to enter rebus mode. However, this key isn't present on standard Mac keyboards. We should support the escape key as well (like Across Lite), as this shouldn't conflict - the only place we currently use Escape is to exit grid selection mode.
- Keyboard focus doesn't return to the grid once the rebus control is closed. You have to click manually.
- Escape doesn't actually work to dismiss the rebus control as the code seems to try to handle, because we never receive an OnChar event for WXK_ESCAPE. XGridCtrl handles this by adding a listener for OnKeyDown instead.

**Comment by mrichards42** [comment]
On windows I expect to use insert to both start entering a rebus and to accept the rebus answer, and escape to cancel the rebus and revert the square's text.
So either: `insert -> "rebus text" -> insert` to accept, or `insert -> "rebus text" -> escape` to reject

Should macs use escape to accept the rebus, or is the existing behavior of rejecting the rebus appropriate?  What are users expecting (esp. if they're coming from Across Lite or Black Ink)?

**Comment by jpd236** [comment]
I think the existing behavior of rejecting the rebus is still appropriate. This is how Across Lite works - escape will let you start entering a rebus, but if you type some letters and hit escape again, it closes the rebus box and makes no changes.

As for Black Ink, as far as I can tell it has a custom shortcut (Command+Option+M), and escape doesn't work either to enter the rebus, exit the rebus, or accept the rebus answer.

**Comment by jpd236** [comment]
(Personally, the way I expect to finish entering my rebus answer is to hit Enter/Return, on any platform).

**Comment by mrichards42** [comment]
works for me
