### ISSUE TITLE
Improve sizing system for non-square grids

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#93]
(Forked from comments in #91)

Comments from there:

"When I tried opening up a jpz rows garden, one thing that drove me nuts is the "feature" where the grid tries to autosize when you change the window size (and sticks to that size and won't let you change it). It seems like it only scales as a square, which means I can't increase the width of the puzzle at all (without changing the size of the window). I'm not sure if you saw that behavior as well, since it might only show up in certain grid/clue pane arrangements.

...

Forcing the grid to be square was probably misguided, but it was done on purpose: ae368c3. It might be worth adjusting that code to scale based on the grid's actual dimensions and see if it produces reasonable results. If it turns out to just be a mess, we can revert to the previous behavior, which I believe was scaling everything proportionally when the window resizes."

**Comment by mrichards42** [comment]
I didn't make a PR for this or tag it in any of the commits, but I believe this should be fixed as of 0f3b17f ([this](https://github.com/mrichards42/xword/compare/cfca9f0b2f7f48cabac22a7d910612ace3732942..0f3b17f09ea47857598c3b7297b5c5cc89e90154) being the relevant diff).

The new code doesn't force the grid pane to be any particular dimensions. The only custom behavior is now (1) adjacent cluelists are the same size, and (2) everything scales proportionally when you resize the window.
