### ISSUE TITLE
preference for self-closed vs. explicit XML tags?

### ISSUE THREAD

**Issue by saweyer** [mrichards42/xword#95]
the .jpz files generated by XWord can't be opened by
    Crossword Compiler  applet (when embedded in .js applet after appropriate \" quoting)

nor by Crossword Nexus viewer:
     https://crosswordnexus.com/solve/

the problem seems to be self-closed syntax (generated by XWord)
e.g., <cell x="1" y="1" solution="A" number="1"/>

and explicit syntax (expected by CC and Nexus)
e.g., <cell x="1" y="1" solution="A" number="1"></cell>

(I verified this by manually editing the XWord-generated .jpz file into explicit syntax;
and then .jpz worked with both CC and Nexus)

I know that both are valid, and that self-closed is "recommended" by W3C,
but rather than fix those (and possibly other) apps/applets that accept .jpz?

might it be possible to add a preference to XWord so that it will generate either syntax?
thanks
Steve

**Comment by saweyer** [comment]
oops -- I should've previewed to make sure the XML examples made it thru.  trying again:

self-closed syntax (generated by XWord)
e.g., &lt;cell x="1" y="1" solution="A" number="1"/&gt;

and explicit syntax (expected by CC and Nexus)
e.g., &lt;cell x="1" y="1" solution="A" number="1"&gt;&lt;/cell&gt;

**Comment by jpd236** [comment]
Hmm, I don't think that was a problem when I tested. Rather it was the empty "<:anonymous />" tag that was added to the metadata section (fixed by https://github.com/mrichards42/xword/pull/88). If you take a JPZ file saved by XWord and remove that tag while leaving the self-closing tags alone, does that open in Crossword Nexus / the Crossword Compiler applet?

**Comment by saweyer** [comment]
hi Jeff,

I unzippped the generated .jpz
then removed the <:anonymous/> tag
then it opened just fine in Crossword Nexus

so my mistake — it didn’t have to do with self-closing tags — 

and it appears the problem was XWord’s added <:anonymous/:> tag

so maybe an XWord preference to not add <:anonymous/:>

or Alex, maybe you could ignore it ?


Steve

**Comment by jpd236** [comment]
It's a bug that it even got there in the first place - so no need to add a preference to control it; we just shouldn't write it as it violates the spec.

This is fixed in the source code, but pending a new release of the Xword app, which is something that @mrichards42 and I have been working on.

**Comment by saweyer** [comment]
great. thanks for quick replies.

btw, I’m using the Mac version (on Catalina) alpha4
	https://github.com/jpd236/xword/releases

**Comment by jpd236** [comment]
Oh, okay - I didn't know anyone else using those builds. I went ahead and cut alpha5 with the fix for this, so feel free to give that a try: https://github.com/jpd236/xword/releases/tag/0.6.2-ci-alpha5. Hopefully there'll be a more "official" release here soon but these should do in the meantime!

**Comment by saweyer** [comment]
yep that worked — I can open .jpz directly successfully in Crossword Solver w/ no editing.

thanks
